apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-pod
  template:
    metadata:
      labels:
        app: multi-pod
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.22.1
          ports:
            - containerPort: 80

        - name: busybox-container
          image: busybox:1.34.1
          command:
            - sleep
            - "3600"

        - name: postgres-container
          image: postgres:13.4
          ports:
            - containerPort: 5432
          

        - name: mysql-container
          image: mysql:8.0.26
          ports:
            - containerPort: 3306
          

        - name: alpine-container
          image: alpine:3.15
          
