version: '3'

services:
  db:
    image: "postgres:9.6.5"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - env_file

  extra_postgres:
    image: "postgres:latest"
    volumes:
      - "extra_dbdata:/var/lib/postgresql/data"  # Changed to a separate volume
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    depends_on:
      - db

  extra_alpine:
    image: "alpine:latest"
    command: ["sleep", "3600"]

  redis:
    image: "redis:6.2.5"

  busybox:
    image: "busybox:1.34.1"
    command: ["sleep", "3600"]

  flaskapp:
    build: .
    env_file:
      - env_file
    volumes:
      - .:/opt/services/flaskapp/src
    depends_on:
      - db

  nginx:
    image: "nginx:1.13.5"

volumes:
  dbdata:  # This declares the named volume for the db service
  extra_dbdata:  # Separate named volume for the extra_postgres service
